on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: uv tool install git+https://tjpnz:${{ secrets.GH_PAT }}@github.com/tjpnz/tjpdotnz-sitegen.git

      - run: sitegen build site _pages

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _pages

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v4
